name: Jack Hughes
bio: "Jack Hughes is an experienced software developer with 30+ years experience writing products for Microsoft Windows based operating systems as well as many years experience hosting websites on Linux and Windows including e-commerce and CMS systems."
avatar: "/images/shy-jack.jpg"
