copyright: "Jack Hughes"

# Home page meta description
description: "The Tech Teapot blog is the online home of Jack Hughes and concentrates on open source network management software"

style:
  vars:
    highlightColor: "#e2852d" # Override highlight color
    # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
    # Take care of different quotes OR escaping symbols in these params if necessary
    fontFamilyPrimary: "'Open Sans', Helvetica, Arial, sans-serif"
    fontFamilySecondary: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

logo:
  image: "images/techteapot-logo.png"
  title: "The Tech Teapot"
  subtitle: "Your daily IT cuppa"

sidebar:
  home: "right" # Configure layout for home page
  list: "left"  # Configure layout for list pages
  single: false # Configure layout for single pages
  # Enable widgets in given order
  widgets: ["search", "authorbio", "authorstackoverflow", "social", "recent", "categories", "links", "taglist"]

widgets:
  recent_num: 5 # Number of articles in the "recent" widget
  tags_counter: false

widgets:
  social:
    linkedin: "jack-hughes-16662613"
    github: "digitalbricklayer"

authorbox: false # Authorbox is broken with Roadster theme

pager: true  # Show pager navigation (prev/next links) at the bottom of pages

# Include custom CSS files
customCSS: ["css/image.css"]

# Include custom JS files
customJS: []

# Order of post meta information
post_meta: ["author", "date", "categories"]
dateformat: "2006-01-02"
# Load jquery for the gallery only
galleryLoadJQuery: true

opengraph: true
schema: true
twitter_cards: true
